---
- name: Try to use ibm_svcinfo_command (requires paramiko)
  hosts: FS5300
  gather_facts: false
  tasks:
    - name: Collect vdisk sizes in bytes (without rounding)
      ibm.storage_virtualize.ibm_svcinfo_command:
        clustername: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        command: svcinfo lsvdisk -bytes
      register: lsvdisk_bytes
